# rule fastp: trim reads
# rule assembly
# rule check assembly quality
# rule remove poor assembled genomes
# rule kraken
# rule annotate

from snakemake.utils import validate
import pandas as pd
import os

# ----- load config file ----- #

configfile: "config/config.yaml"

# ----- define functions ----- #
def _read_file_names(indir, extension='_1.fastq.gz'):
  return {x.split(extension)[0] for x in os.listdir(indir) if x.endswith(extension)}

# ----- params ----- #
samples = list(_read_file_names("data/reads/", extension='_1.fastq.gz'))
print(samples)

fastas_pass = list(_read_file_names("out/skesa/", extension='.fasta'))
print(fastas_pass)

# ----- start execution of the rules ----- #

rule fastp:
    input:
        expand("out/fastp/reads/{sample}_1.fastq.gz", sample=samples),
        expand("out/fastp/reads/{sample}_2.fastq.gz", sample=samples),
        expand("out/fastp/reports/{sample}.json", sample=samples),
        expand("out/fastp/reports/{sample}.html", sample=samples)

rule run_fastp:
    input:
        R1=lambda wildcards: "data/reads/{sample}_1.fastq.gz",
        R2=lambda wildcards: "data/reads/{sample}_2.fastq.gz"
    output:
        r1="out/fastp/reads/{sample}_1.fastq.gz",
        r2="out/fastp/reads/{sample}_2.fastq.gz",
        json="out/fastp/reports/{sample}.json",
        html="out/fastp/reports/{sample}.html"
    threads: 2
    conda: "envs/fastp.yaml"
    shell:
        """
        fastp -i {input.R1} -I {input.R2} -o {output.r1} -O {output.r2} -j {output.json} -h {output.html}
        """

rule assembly:
    input:
        expand("out/shovill/{sample}", sample=samples)

rule run_assembly:
    input:
        r1=lambda wildcards: "out/fastp/reads/{sample}_1.fastq.gz",
        r2=lambda wildcards: "out/fastp/reads/{sample}_2.fastq.gz"
    output:
        fasta=directory("out/shovill/{sample}")
    threads: 8
    conda: "envs/shovill.yaml"
    shell:
        """
        shovill --outdir {output} --R1 {input.r1} --R2 {input.r2} --tmpdir "/tmp/"
        """

rule fast_assembly:
    input:
        expand("out/skesa/{sample}.fasta", sample=samples)

rule run_fast_assembly:
    input:
        r1=lambda wildcards: "out/fastp/reads/{sample}_1.fastq.gz",
        r2=lambda wildcards: "out/fastp/reads/{sample}_2.fastq.gz" 
    output:
        fasta="out/skesa/{sample}.fasta"
    threads: 12
    conda: "envs/skesa.yaml"
    shell:
        """
        skesa --cores 12 --reads {input.r1} {input.r2} --contigs_out {output}
        """

rule quast:
    input: expand("out/quast/{sample}", sample=samples)

rule run_quast:
    input:
        fasta=lambda wildcards: "out/skesa/{sample}.fasta"
    output: directory("out/quast/{sample}")
    threads: 2
    log: "out/logs/quast/{sample}.log"
    conda: "envs/quast.yaml"
    shell:
        """
        quast -o {output} -t 8 --no-plots --no-html --no-icarus {input}
        """

rule check_quast:
    input:
        dir="out/quast"
    output:
        quast="out/quast/quast_output.tsv",
        filtered="out/quast/quast_output_f.tsv",
        removed="out/quast/quast_output_toremove.tsv"
    shell:
        """
        python workflow/scripts/twist_quast_output.py {input}
        """

rule filter_quast:
    input:
        fastasdir="out/skesa",
        quastout="out/quast/quast_output_toremove.tsv",
        removeddir="data/removed_fastas"
    output:
        "out/fastas_moved.txt"
    shell:
        """
        python workflow/scripts/move_qc_fastas.py {input.fastasdir} {input.quastout} {input.removeddir}
        """

#rule kraken:
#rule run_kraken:

rule annotate:
    input:
        expand("data/gffs/{sample}.gff", sample=fastas_pass)

rule run_annotate:
    input:
        fasta="out/skesa/{sample}.fasta"
    output: "data/gffs/{sample}.gff"
    log: "out/logs/prokka_{sample}.log"
    threads: 12
    conda: "envs/prokka.yaml"
    shell:
        """
        prokka --outdir out/prokka/{wildcards.sample} --prefix {wildcards.sample} {input.fasta}
        """
